language: python
python:
    - "3.4"
install: python3 -m pip install -r requirements.txt
env:
    - CONFIG_PATH=photos.config.TravisConfig
before_script:
    - psql -c 'create database "photos-test";' -U postgres
script:
    - PYTHONPATH=. python3 tests/unit.py
